name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run: npm run build --if-present

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2.1.0
      with: 
        project_id: ${{secrets.GOOGLE_PROJECT}}
        service_acccount_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        export_default_credentials: true 

    - name: build and push the docker image
      env: 
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev
        docker build -t asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/nginx:latest .
        docker push asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/nginx:latest
        